language: java
jdk:
- oraclejdk8
services:
  - mysql
branches:
  only:
  - master
before_install:
- cd TalosQuestsBackend
- mysql -e 'CREATE DATABASE talosquests;'
script: mvn clean test cobertura:cobertura coveralls:report | egrep -v "(maps\.googleapis\.com|^Hibernate:|^\[DEBUG\])"
after_success:

- bash <(curl -s https://codecov.io/bash)
