language: java
jdk:
- oraclejdk8
services:
  - mysql
branches:
  only:
  - master
before_install:
- cd TalosQuestsBackend
- mysql -e 'CREATE DATABASE talosquests;'
script: mvn clean verify -DskipTests
after_success:
- mvn clean site coveralls:report | egrep -v "(maps\.googleapis\.com|^Hibernate:|^\[DEBUG\])"
