language: java
jdk:
  - oraclejdk8
branches:
  only:
  - master
before_install: cd TalosQuestsBackend
script: mvn clean verify -DskipTests
after_success:
  - mvn -q clean cobertura:cobertura coveralls:report | egrep -v "(^Hibernate:|^\[DEBUG\])"
