language: java
jdk:
- oraclejdk8
services:
  - mysql
branches:
  only:
  - master
before_install:
- cd TalosQuestsBackend
- mysql -e 'CREATE DATABASE talosquests;'
script: mvn clean verify -DskipTests
after_success:
- mvn -q clean cobertura:cobertura coveralls:report -Dcobertura.report.format=xml | egrep -v "(maps\.googleapis\.com|^Hibernate:|^\[DEBUG\])"